---
title: "Unsupervised Learning: Clustering"
author: "Jane Kathambi"
date: "18 July 2018"
output: 
  html_document:
    keep_md: yes
    number_sections: yes
    theme: united
    toc: yes
    toc_depth: 4
    toc_float:
      collapsed: yes
      smooth_scroll: yes
---
# Introduction
Unsupervised learning refers to a set of statistical techniques for exploring and discovering knowledge, from a multivariate data, without building a predictive models.

It makes it possible to visualize the relationship between variables, as well as, to identify groups of similar individuals (or observations).

The most popular unsupervised learning methods, include:

* Principal component methods, which consist of summarizing and visualizing the most important information contained in a multivariate data set.

* Cluster analysis for identifying groups of observations with similar profile according to a specific criteria. These techniques include: 
    + hierarchical clustering and 
    + k-means clustering.

# Principal component methods
Principal component methods allows us to summarize and visualize the most important information contained in a multivariate data set.

The type of principal component methods to use depends on *variable types* contained in the data set. These methods include:

* *Principal Component Analysis (PCA)*, which is one of the most popular multivariate analysis method. The goal of PCA is to summarize the information contained in a *continuous (i.e, quantitative) multivariate data* by reducing the dimensionality of the data without loosing important information.

* *Correspondence Analysis (CA)*, which is an extension of the principal component analysis for analyzing *a large contingency table formed by two qualitative variables (or categorical data)*.

* *Multiple Correspondence Analysis (MCA)*, which is an adaptation of CA to *a data table containing more than two categorical variables*.

