---
title: " Cleaning MBTA ridership data"
author: "Jane Kathambi"
date: "8 June 2018"
output: 
  html_document:
    keep_md: yes
    theme: united
    toc: yes
    toc_depth: 4
    toc_float:
      collapsed: yes
      smooth_scroll: yes
---

# .

# Introduction
The Massachusetts Bay Transportation Authority ("MBTA" or just "the T" for short) manages America's oldest subway, as well as Greater Boston's commuter rail, ferry, and bus systems.

We are going to clean this data step by step.

The dataset is stored as an Excel spreadsheet called mbta.xlsx in the data folder that is inside the data cleaning folder. We will use the read_excel() function from Hadley Wickham's readxl package to import it.

In most cases excel spreadhseets have some rows that need to be skipped e.g a title. However, the first time one imports a dataset, they might not know how many rows need to be skipped. So one needs to import the data and explore the first few rows, identify the ones that need to be ommited and omit them and save the resulting data frame to a new name. If one knows how many rows to skip then they can go ahead and skip them while importing. 


# Loading the required packages
We will import the excel data using the readxl package. We will require tidyr for data cleaning contained in the tidyverse package

```{r}
#Load the readxl library
library(readxl)

#Load the tidyverse library
library(tidyverse)

```

