---
title: "Numerical Summaries"
author: "Jane Kathambi"
date: "8 June 2018"
output: 
  html_document:
    keep_md: yes
    theme: united
    number_sections: true
    toc: yes
    toc_depth: 5
    toc_float:
      collapsed: yes
      smooth_scroll: yes
---

# Introduction
We are going to look at numerical summaries.
We will explore the four characteristics of distribution which are:

1. Measures of center, 
2. Measures of variability(spread),
3. The shape of the distribution,
4. Outliers

## Measure of center

Below are measures of tendancy and an explanation of which  work well with what data. 
**Mean**-> Balance point of the data. Very sensitive to extreme values i.e affected by skewed data so not a good choice.

**Median**-> Divides the data into a lower half and a upper half. Better than mean when working with skewed data.

**Mode**-> Most common entries.

So which one to use?

1. For highly skewed data median is the best, but mean for lowly skewed data.
2. For non skewed data all of them.

## Measure of Variability

**sd**-> Most commonly used. But does not work well with highly skewed data i.e extreme values

**Variance**-> shows how much the data varies from the measure of center. Not widely used because it is not in the same units with the original data so sd is better.

**IQR**-> best used with skewed data as it does not change

**Range**->Not often used because it does not work well with skewed data i.e extreme values.

So which one to use?

1. For highly skewed data IQR is the best, but sd for lowly skewed data.
2. For non skewed data all of them.

so median and IQR measure the central tendency and spread, respectively, but are robust to outliers and non-normal data.

## The shape of the distribution

The shape of the distribution can be described in terms of the modality and the skew.

### Modality

The number of prominent humps that show up in the distribution. If:

1. Single mode i.e bell curve, the modality is called unimodal.
2. Two prominent modes, bimodal.
3. Three or more modes, multimodal.
4. No distinct mode because the distribution is flat across all values, uniform.
 
### Skew
If a distribution has a:

1. Long tail that stretches out to the right, the distribution is referred to as right-skewed.
2. Long tail that stretches out to the left, the distribution is referred to as left-skewed.
3. None of the tails is longer than the other, the distribution is referred to as symmetric

Highly skewed distributions can make it very difficult to learn anything from a visualization. Transformations can be helpful in revealing the more subtle structure. One can use logarithm or square root fucntions to transform the heavily skewed data.




### Transformations

We will focus on the population variable, which exhibits strong right skew, and transform it with the natural logarithm function (log() in R).


## Outliers







